services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - ${VITE_APP_PORT:-5173}:5173 # for vite
    volumes:
      - ./:/var/www
      - ./docker/php/supervisord.d/queue-worker.conf:/etc/supervisor/conf.d/queue-worker.conf
      - ./docker/php/supervisord.d/schedule.conf:/etc/supervisor/conf.d/schedule.conf
      - ./docker/php/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    working_dir: /var/www/src
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: mysql:8.2
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - '${DATABASE_PORT:-3310}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-restaurants_revenue_order}
      MYSQL_USER: ${MYSQL_USER:-restaurants_revenue_order}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      TZ: ${TZ:-Asia/Tokyo}
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - '${APP_PORT:-18090}:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network

  redis:
    image: redis:alpine
    volumes:
      - redis-store:/data
    ports:
      - '${REDIS_PORT:-6379}:6379'
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "${MAIL_PORT:-8025}:8025"
      - "${MAILHOG_SMTP_PORT:-1025}:1025"
    volumes:
      - ./mailhog/maildir:/maildir
    command: [ "-storage=maildir", "-maildir-path=/maildir" ]
    networks:
      - app-network

volumes:
  db-store:
  redis-store:

networks:
  app-network:
    driver: bridge
